@startuml Diagrama_Casos

/'Diagrama de casos de uso
+ Poner nombre
+ Responder examen contiene navegar y terminar
+ Descargar -> Obtener certificado
    + User cambia sus datos (Nuevo caso de uso)
    + Admin cambia contraseña de user (Nuevo caso de uso)
'/

'PARÁMETROS DE APARIENCIA

skinparam NoteBackgroundColor transparent
skinparam NoteBorderColor transparent
skinparam actorStyle awesome


'DECLARACIONES

Rectangle CodeTest {
    "Crear Examen" as (crear_examen)
    "Registrar Usuario" as (registrar_usuario)
    "Iniciar Sesion" as (Iniciar_sesion)
    "Cerrar Sesion" as (Cerrar_sesion)
    "Consultar FAQ" as (consultar_FAQ)
    "Buscar Examen" as (Escoger_examen)
    "Responder Examen" as (Responder_Examen)
    "Obtener Certificado" as (Obtener_certificado)
    "Resetear contraseña" as (Resetear_contraseña)
    "Editar perfil" as (Editar_perfil)
}

left to right direction
actor "Administrador" as Administrador #5081B2
actor "Estudiante" as Estudiante #78C6D2

'RELACIONES

Administrador --- crear_examen
Administrador --- registrar_usuario
Administrador --- Resetear_contraseña

Estudiante --- Responder_Examen
Estudiante --- Iniciar_sesion
Estudiante --- Cerrar_sesion
Estudiante --- consultar_FAQ
Estudiante --- Escoger_examen
Estudiante --- Obtener_certificado
Estudiante --- Editar_perfil

@enduml