/'Diagrama de estado
    + Faltaron las transiciones
+ Faltó el nodo de fin
+ Quitar el tema (Bolita)
- Modelar el estado del sistema, no las actividades.

'/

@startuml D_Estado_Usos

skinparam NoteBackgroundColor transparent
skinparam NoteBorderColor transparent
skinparam backgroundColor white
hide members
skinparam actorStyle awesome

/' ESTILOS '/

skinparam state{
    FontSize 12
    BackgroundColor #E7F5F7

}

/' DIAGRAMA PARA EL ADMIN '/ 

state Admin #009caa{
    state " " as Estado_Inicial_Admin
    state "Registrando Usuario" as Usuario_Registrado
    state "Creando Examen" as Crear_Examen 
    [*] --> Estado_Inicial_Admin
    Estado_Inicial_Admin --> Usuario_Registrado : Registrar usuario
    Usuario_Registrado --> Crear_Examen : Crear Examen
    Crear_Examen --> [*]
}

/' DIAGRAMA PARA EL ESTUDIANTE '/

state Estudiante #83c5be{
    state "Seleccionando Tipo de Examen" as Tipo_Seleccionado
    state "Consultando FAQ" as Consultar_FAQ
    state "Obteniendo Certificado" as Solicitar_Certificado
    state "Cerrando Sesion" as Cerrar_Sesion

    [*]-->Tipo_Seleccionado: Buscar Examen
    Tipo_Seleccionado -r-> Consultar_FAQ: Consultar FAQ
    Consultar_FAQ -d-> Responder_Examen: Responder Examen
    Responder_Examen -l-> Solicitar_Certificado: Obtener Certificado
    Solicitar_Certificado -d-> Cerrar_Sesion: Cerrar Sesion
    Cerrar_Sesion -r-> [*]
}


@enduml