@startuml clase_analisis 

actor Administrador
boundary "IU crear examen" as crear_examen
control "Generador de examen" as controlador 
entity Examen as publicar_examen 
entity Pregunta as añadir_pregunta

Administrador -r- crear_examen
crear_examen -r- controlador
controlador -- añadir_pregunta
controlador -- publicar_examen

@enduml