@startuml viewsClassDiagram
skinparam ClassBackgroundColor white
skinparam classAttributeIconSize 0
hide circle

class Coordinate
enum Error
enum Color
class StartController
class PlayController
class ResumeController

class  BoardView{
    + write(StartController)
}

class  ErrorView{
    + writeln(Error)
}

class  PlayView{
    + play(PlayController)
}

class  ResumeView{
    + resume(ResumeController): boolean
}

class StartView{
    + start(StartController)
}

class  MovementView{
    + interact()
}

class  ColorView{
    + write(Color)
}

enum  Message{
    + TITLE
    + HORIZONTAL_LINE
    + VERTICAL_LINE
    + ACTION_COMMAND
    + UNDO_COMMAND
    + REDO_COMMAND
    + ENTER_COORDINATE_TO_PUT
    + COORDINATE_TO_PUT
    + COORDINATE_TO_REMOVE
    + COORDINATE_TO_MOVE
    + PLAYER_WIN
    + RESUME
    + writeln()
    + write()
}

class  PlayerView{
    
}

class  CoordinateView{
    + read(): Coordinate
}

PlayerView *-down-> StartView
PlayerView *-down-> PlayView
PlayerView *-down-> ResumeView
StartView ..> Message
StartView ..> BoardView
StartView -down-> StartController
BoardView ..> ColorView
BoardView ..> Message
PlayView ..> Message
PlayView ..> BoardView
PlayView ..> MovementView
MovementView ..> ErrorView
ResumeView ..> Message
ResumeView -down-> ResumeController
BoardView .down.> Coordinate
MovementView .down.> Coordinate
BoardView .down.> StartController
BoardView .down.> Color
MovementView .down.> Error
ErrorView .down.> Error
PlayView -down-> PlayController
ColorView .down.> Color
CoordinateView .down.> Coordinate
MovementView ..> CoordinateView
@enduml