@startuml Diagrama_Casos

/'Actores:

1. Estudiante 
2. Administrador

Casos de uso:

1. Crear examen (Administrador)
2. Registrar usuario (Administrador)
3. Iniciar sesion (Estudiante)
4. Cerrar sesion (Estudiante)
5. Consultar FAQ (Estudiante)
6. Escoger tipo de examen (Estudiante)
7. Responder examen (Estudiante)
8. Navegar (Estudiante)
9. Terminar examen (Estudiante)
10. Descargar certificado (Estudiante)

Casos de uso priorizados:

Crear examen
Registrar usuario
Responder examen'/

'PARÁMETROS DE APARIENCIA

skinparam NoteBackgroundColor transparent
skinparam NoteBorderColor transparent
skinparam actorStyle awesome


'DECLARACIONES

Rectangle Aplicación {
    "Crear Examen" as (crear_examen)
    "Registrar Usuario" as (registrar_usuario)
    "Iniciar Sesion" as (Iniciar_sesion)
    "Cerrar Sesion" as (Cerrar_sesion)
    "Consultar FAQ" as (consultar_FAQ)
    "Escoger Examen" as (Escoger_examen)
    "Responder Examen" as (Responder_Examen)
    "Navegar" as (Navegar)
    "Terminar Examen" as (Terminar_Examen)
    "Descargar Certificado" as (Descargar_Certificado)
}

left to right direction
actor "Administrador" as Administrador #5081B2
actor "Estudiante" as Estudiante #78C6D2

'RELACIONES

Administrador --- crear_examen
Administrador --- registrar_usuario

Estudiante --- Responder_Examen
Estudiante --- Iniciar_sesion
Estudiante --- Cerrar_sesion
Estudiante --- consultar_FAQ
Estudiante --- Navegar
Estudiante --- Terminar_Examen
Estudiante --- Escoger_examen
Estudiante --- Descargar_Certificado

@enduml