/'1. Registrando
2. Iniciando Sesin - 
3. Creando examenes
4. Escogiendo nmero de preguntas y duracin
5. Escogiendo tipo de examen
6. Mostrando instrucciones
7. Presentando examen
8. Viendo progreso
9. Navegando hacia atrs
10. Navegando hacia adelante
11. Terminando examen
11.1 Tiempo acabado
11.2 Presentando mensaje de tiempo acabado
12. Viendo resultado
13. Recibiendo explicaciones
14. Recibiendo certificado
'/

@startuml estadop

/' ESTILOS '/

skinparam state{
    BackgroundColor #EADDE7
    FontSize 12
}

state " " as Estado_Inicial

[*] --> Estado_Inicial
Estado_Inicial --> CreandoExamen : Iniciando Creación de Examen


/' DECLARACIONES CREANDO EXAMEN'/

state CreandoExamen {
 state EscogiendoPreguntas
 state EscogiendoDuracion
}

/' DECLARACIONES PRESENTANDO EXAMEN '/

state PresentandoExamen {
    state PreguntaRespondida
    state condicionPregunta <<choice>>
    state navegandoAdelante
    state navegandoAtras
}

/' ESTADO CREANDO EXAMEN '/

EscogiendoPreguntas -r-> EscogiendoDuracion
CreandoExamen -r-> EscogiendoTipoDeExamen: escogerTipo()
EscogiendoTipoDeExamen -r-> MostrandoInstrucciones: mostrarInstrucciones()
MostrandoInstrucciones -d--> PresentandoExamen: presentar()

/' ESTADO PRESENTANDO EXAMEN '/

PreguntaRespondida --> condicionPregunta
condicionPregunta --> navegandoAtras
condicionPregunta --> navegandoAdelante
navegandoAtras --> navegandoAdelante
navegandoAdelante --> PreguntaRespondida : SeleccionarRespuesta()

/' ESTADO TERMINANDO EXAMEN '/

PresentandoExamen -l-> TerminandoExamen : [TiempoAcabo || No restan preguntas]

TerminandoExamen -l-> PresentandoTiempo: mostrarTiempo()
PresentandoTiempo -d-> ViendoRespuestas: verRespuestas()
ViendoRespuestas -r-> RecibiendoExplicaciones: verExplicacion()
RecibiendoExplicaciones -r-> RecibiendoCertificado: solicitarCertificado()
RecibiendoCertificado -r-> [*]: EstadoFinal

@enduml