@startUML designClassesUseCase2

<style>
classDiagram {
  class {
      header {
        FontStyle bold
      }
  }
}
</style>

!theme plain
hide circle

skinparam actorStyle awesome
allowmixing

actor Student

'' NAVBAR

Class "<<JPanel>> \n Navbar " as Navbar {
}

Class "<<JLabel>> \n InteractiveIcon" as InteractiveIcon {
    - labelIcon: ImageIcon
    - labelAction: mouseListener
    + interactiveIcon(image, mouseListener)
}

InteractiveIcon -l- Navbar: 3

'' TESTVIEWPANEL

Class "<<JPanel>> \n TestViewPanel " as TestViewPanel {

}

Class "<<JPanel>> \n QuestionsListPanel  " as QuestionsListPanel {

}

Class "<<JPanel>> \n TestInfoPanel " as TestInfoPanel {
    - clock: JLabel 
    - answeredQuestions: JLabel
    - testName: JLabel
}

Class "<<JScrollPane>> \n ScrollableQuestionsPanel " as ScrollableQuestionsPanel {

}

Class "<<JButton>> \n BlueButton " as BlueButton {

}

Class "<<JPanel>> \n QuestionPanel  " as QuestionPanel {
    - questionNumber: JLabel
    - questionDomain: JLabel
    - questionDescription: JLabel
    - optionText[]: JTextField
    - optionBox[]: JCheckBox
}

Class "<<JLabel>> \n QuestionDescription" as QuestionDescription {
    - questionType: Boolean
    - text: String
}

Class "<<JFrame>> \n TestView  " as TestView{

}

QuestionPanel "1...*" -- ScrollableQuestionsPanel
TestInfoPanel -- QuestionsListPanel
BlueButton -- TestInfoPanel
ScrollableQuestionsPanel -- QuestionsListPanel
Navbar -l- TestViewPanel
QuestionsListPanel -- TestViewPanel
TestViewPanel -- TestView
QuestionDescription -d-* QuestionPanel

'' SOLUTIONSVIEW

Class "<<JFrame>> \n SolutionsView" as SolutionsView {

    
}

Class "<<JPanel>> \n SolutionsViewPanel  " as SolutionsViewPanel {

}

CLass "<<JPanel>> \n QuestionsSummaryPanel " as QuestionsSummaryPanel {
    - QuestionSummary[]: JLabel
}

Class "<<JScrollPane>> \n ScrollableQuestionsSummaryPanel " as ScrollableQuestionsSummaryPanel {
    - QuestionsSummaryTitle: JLabel
}

Class "<<JPanel>> \n AnswersSummaryPanel" as AnswersSummaryPanel {
    - answersTitle: JLabel
}

Class "<<JScrollPane>> \n ScrollableAnswersPanel" as ScrollableAnswersPanel {

}

Class "<<JPanel>> \n AnswerPanel" as AnswerPanel {
    - option: JTextField
    - optionJustification: JLabel
    - resultIcon: JLabel
}

SolutionsView -r- SolutionsViewPanel
SolutionsViewPanel -- AnswersSummaryPanel
SolutionsViewPanel -- QuestionsSummaryPanel
SolutionsViewPanel -u- Navbar
QuestionsSummaryPanel -- ScrollableQuestionsSummaryPanel
AnswersSummaryPanel -- ScrollableAnswersPanel
ScrollableAnswersPanel -- "1...*" AnswerPanel

'' ANSWERTESTCONTROLLER

Class AnswerTestController{
    loadQuestions()
    saveAnswers()
    loadAnswers()
}

Class Test{

    type: text 
    duration: number
    calification: number

    endTest()
    addQuestion(Question)
    getQuestion()
}

Class Question{

    description: text
    justification: text
    userAnswer: Answer
    rightAnswer: Answer

    addAnwer(Answer)
    answerQuestion(Answer)
}

Class Answer{

    answerType:
}

'' CASO DE USO GETCERTIFICATE

class "<<JFrame>> \n TestListView" as TestListView {

}

class "<<JLayeredPane>> \n TestListViewPanel" as TestListViewPanel {

}

class "<<JPanel>> \n courseListPanel" as courseListPanel {

}

class "<<JPanel>> \n AvailableTestsPanel" as AvailableTestsPanel {
    - AvailableTestsTitle: JLabel
}

class "<<JPanel>> \n AvailableTestScrollablePanel" as AvailableTestScrollablePanel {
    - selectTest[]: JLabel
}

class "<<JPanel>> \n getCertificatePopUp" as getCertificatePopUp {
    
}


TestListView -- TestListViewPanel
TestListViewPanel -- courseListPanel
TestListViewPanel -- AvailableTestsPanel
TestListViewPanel -- getCertificatePopUp
AvailableTestsPanel -- AvailableTestScrollablePanel

Student -r- TestView

TestView -r- AnswerTestController

AnswerTestController -r- SolutionsView

AnswerTestController -d- Test

Question -u-* Test

Answer -r-* Question

@endUML