@startuml clase_analisis 

actor Admin as Administrador
boundary "createTestView" as crear_examen
control "createTest" as controlador
entity Test as publicar_examen
entity Question as añadir_pregunta

Administrador -r- crear_examen
crear_examen -r- controlador
controlador -- añadir_pregunta
controlador -- publicar_examen

@enduml