@startuml clase_analisis 

actor Student as Estudiante
boundary "StudentView" as vista_estudiante
boundary "TestView" as responder_examen
boundary "SolutionsView" as soluciones
control "answerTest" as controlador 
entity Test as examen
entity Question as pregunta

Estudiante -r- vista_estudiante
vista_estudiante -r- responder_examen
responder_examen -r- controlador
controlador -u- soluciones
controlador -- examen
controlador -- pregunta

@enduml