@startuml clase_analisis 
skinparam NoteBackgroundColor transparent
skinparam NoteBorderColor transparent

actor Admin as Administrador
boundary ": CreateTestView" as crear_examen
control ": CreateTest" as controlador
entity ": Test" as publicar_examen
entity ": Question" as añadir_pregunta

Administrador -r--  crear_examen
note on link
1: createTest()
end note
crear_examen -r-- controlador 
note on link
2: newTest(testData) 
end note
controlador -- añadir_pregunta
note on link
3: Question = Question(description, answers)
end note
controlador -- publicar_examen
note on link
4: Test = Test(name, question, duration) 
end note

@enduml