@startuml clase_analisis 

skinparam NoteBackgroundColor transparent
skinparam NoteBorderColor transparent

actor Student as Estudiante
boundary ": TestView" as responder_examen
boundary ": SolutionsView" as soluciones
control ": AnswerTest" as controlador 
entity ": Test" as examen
entity ": Question" as pregunta

Estudiante -r- responder_examen
note on link
1: approveInstructions()
end note
responder_examen -r- controlador
note on link
2: start()
end note
controlador -- pregunta
note on link
3: answerQuestion(userAnswer);
end note
controlador -- examen
note on link
4: endTest()
end note
controlador -u- soluciones
note on link
5: viewSolutions(Question)
end note

@enduml