@startuml clase_analisis 

skinparam NoteBackgroundColor transparent
skinparam NoteBorderColor transparent

actor Student as Estudiante
boundary "getCertificateView" as solicitar_certificado
control "getCertificate" as controlador 
entity Certificate as Certificado

Estudiante -r- solicitar_certificado
note on link
1: getCertificate()
end note
solicitar_certificado -r- controlador
note on link
2: generateCertificate()
end note
controlador -- Certificado
note on link
3: giveCertificate(Certificate)
end note

@enduml