@startuml analysisClassDiagramUC2

actor Student as Estudiante
boundary "TestListView" as test_list
boundary "TestView" as responder_examen
boundary "SolutionsView" as soluciones
control "answerTest" as controlador 
entity Test as examen
entity Question as pregunta

Estudiante -r- test_list
test_list -r- responder_examen
responder_examen -r- controlador
controlador -u- soluciones
controlador -- examen
controlador -- pregunta

@enduml