@startuml analysisClassDiagramUC3

actor Student as Estudiante
boundary "CertificateView" as solicitar_certificado
control "getCertificate" as controlador 
entity Certificate as Certificado

Estudiante -r- solicitar_certificado
solicitar_certificado -r- controlador
controlador -- Certificado

@enduml