@startuml collaborationDiagramUC1
skinparam NoteBackgroundColor transparent
skinparam NoteBorderColor transparent

actor Admin as Administrador
boundary ": CreateTestView" as crear_examen
control ": CreateTest" as controlador
entity ": Test" as publicar_examen
entity ": Question" as añadir_pregunta

Administrador -r--  crear_examen
note on link
1: addTest(name,type,duration)
end note
crear_examen -r-- controlador 
note on link
2: createNewQuestion(Question)
end note
controlador -- añadir_pregunta
note on link
3: addAnswer(Answer)
end note
controlador -- publicar_examen
note on link
4: addQuestion(Question)
end note

@enduml